import React from "react";
import QuranInfo from "../Quran/Chapters_Info/Quran_info.json"; // Adjust the import path as necessary

const surahNames = [
  "الفاتحة",
  "البقرة",
  "آل عمران",
  "النساء",
  "المائدة",
  "الأنعام",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "يونس",
  "هود",
  "يوسف",
  "الرعد",
  "إبراهيم",
  "الحجر",
  "النحل",
  "الإسراء",
  "الكهف",
  "مريم",
  "طه",
  "الأنبياء",
  "الحج",
  "المؤمنون",
  "النور",
  "الفرقان",
  "الشعراء",
  "النمل",
  "القصص",
  "العنكبوت",
  "الروم",
  "لقمان",
  "السجدة",
  "الأحزاب",
  "سبأ",
  "فاطر",
  "يس",
  "الصافات",
  "ص",
  "الزمر",
  "غافر",
  "فصلت",
  "الشورى",
  "الزخرف",
  "الدخان",
  "الجاثية",
  "الأحقاف",
  "محمد",
  "الفتح",
  "الحجرات",
  "ق",
  "الذاريات",
  "الطور",
  "النجم",
  "القمر",
  "الرحمن",
  "الواقعة",
  "الحديد",
  "المجادلة",
  "الحشر",
  "الممتحنة",
  "الصف",
  "الجمعة",
  "المنافقون",
  "التغابن",
  "الطلاق",
  "التحريم",
  "الملك",
  "القلم",
  "الحاقة",
  "المعارج",
  "نوح",
  "الجن",
  "المزمل",
  "المدثر",
  "القيامة",
  "الإنسان",
  "المرسلات",
  "النبأ",
  "النازعات",
  "عبس",
  "التكوير",
  "الإنفطار",
  "المطففين",
  "الإنشقاق",
  "البروج",
  "الطارق",
  "الأعلى",
  "الغاشية",
  "الفجر",
  "البلد",
  "الشمس",
  "الليل",
  "الضحى",
  "الشرح",
  "التين",
  "العلق",
  "القدر",
  "البينة",
  "الزلزلة",
  "العاديات",
  "القارعة",
  "التكاثر",
  "العصر",
  "الهمزة",
  "الفيل",
  "قريش",
  "الماعون",
  "الكوثر",
  "الكافرون",
  "النصر",
  "المسد",
  "الإخلاص",
  "الفلق",
  "الناس",
];

const GetVerseInfo = ({ verse }) => {
  // Function to find verse information by ID
  const findVerseById = (id) => {
    return QuranInfo.find((v) => v.id === id);
  };

  // Retrieve verse information based on verse.id
  const verseInfo = findVerseById(verse.id);

  const verseSurahNumber = verseInfo.verse_key.split(":")[0];
  // Return the verse information in an array
  return verseInfo
    ? [
        {
          key: "اسم السورة",
          value: surahNames[verseSurahNumber - 1],
        },
        {
          key: "رقم الاية",
          value: verseInfo.verse_number,
        },
        {
          key: "رقم الجزء",
          value: verseInfo.juz_number,
        },
        {
          key: "رقم الحزب",
          value: verseInfo.hizb_number,
        },
        {
          key: "الصفحة",
          value: verseInfo.page_number,
        },
      ]
    : [];
};

export default GetVerseInfo;
